name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        conda install pytest
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
sleep
echo 
toilet -f big -F gay by Cyber X Santri Assyaiban
echo $gred"selamat datang"
echo
sleep 2
echo
echo $yelow"silahkan di pilih"
echo 
echo $green"1.)kamu mau gk jadi pacar aku ?"
echo
echo $red"0.keluar aja"
echo $white
read -p"pilih yang mana : " cantik

if [ $cantik = 1 ] || [$cantik = 1 ]
then
clear
toilet -f big -F gay by Cyber X Santri Assyaiban
echo $cyan"kalo mau bilang aja gk usah malu malutinggal bilang aja"
sleep 2 
alhamdulillah kalau mau
fi

if [$cantik = 0 ] || [$cantik = 0 ]
then
clear
echo $green
fi
figlet "BYE"
echo $cyan"goodbye hope you are happy with other than me"
sleep 3
exit
fi
